kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry-data-01
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: gp2
  volumeMode: Filesystem
